version: "3.8"
services:
  db:
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=secstorage
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d